on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Binaries

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build Binary
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        goosarch:
          - 'darwin/amd64'
          - 'darwin/arm64'
          - 'linux/amd64'
          - 'linux/arm'
          - 'linux/arm64'
          - 'windows/amd64'
          - 'windows/arm'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.18'
      - name: Get Build Matrix Info and Set Variables
        run: |
          CGO_ENABLED=1
          GOOSARCH=${{matrix.goosarch}}
          GOOS=${GOOSARCH%/*}
          GOARCH=${GOOSARCH#*/}
          BINARY_NAME=ledfx-$GOOS-$GOARCH
          echo "BINARY_NAME=$BINARY_NAME" >> $GITHUB_ENV
          echo "GOOS=$GOOS" >> $GITHUB_ENV
          echo "GOARCH=$GOARCH" >> $GITHUB_ENV

          if [ $GOOS = "windows" ]; then
            BINARY_NAME+='.exe'
          fi

      - name: Install Required Dependencies
        run: |
          echo "Installing dependencies"
          sudo apt-get install gcc-aarch64-linux-gnu libc6-dev-arm64-cross
          dpkg --add-architecture $GOARCH
          sudo apt-get install libasound-dev:$GOARCH portaudio19-dev:$GOARCH libportaudio2:$GOARCH libportaudiocpp0:$GOARCH aubio-tools:$GOARCH libaubio-dev:$GOARCH libaubio-doc:$GOARCH
      - name: Build
        run: |
          if [ $env.GOOs = "windows" ]; then
            go build -o "$BINARY_NAME" -v -ldflags "-H=windowsgui"
          else
            go build -o "$BINARY_NAME" -v
          fi
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.BINARY_NAME }}
          path: ./${{ env.BINARY_NAME }}
