on:
  push:
    branches: [main]
  workflow_dispatch:

name: Build Windows x64 Binary

jobs:
 build_win:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Set up Build Environment 
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: |
            git
            make
            unzip
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-go
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-portaudio
    - name: Get aubio
      run: |
        export CYGPATH=$(cygpath -m /)
        curl -o aubio.zip https://www.ledfx.app/downloads/aubio-0.5.0-alpha-win64.zip
        unzip aubio.zip
        mv aubio-0.5.0-alpha-win64/bin/* $CYGPATH/mingw64/bin/
        mv aubio-0.5.0-alpha-win64/lib/pkgconfig/aubio.pc $CYGPATH/mingw64/lib/pkgconfig
        mv aubio-0.5.0-alpha-win64/lib/* $CYGPATH/mingw64/lib/
        mv aubio-0.5.0-alpha-win64/include/* $CYGPATH/mingw64/include/
         
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        submodules: true
    - name: Build LedFx
      run: |
         go build -o 'LedFx.exe' -v
    - name: Package LedFx
      run: |
         export CYGPATH=$(cygpath -m /)
         mkdir LedFx_Builds/
         mv LedFx.exe LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libaubio-5.dll LedFx_Builds/
         cp $CYGPATH/mingw64/bin/libportaudio.dll LedFx_Builds/   
    - name: Upload LedFx Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LedFx-windows-amd64-${{ github.sha }}
        path: LedFx_Builds/
